steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/cbd-test/yo:a'
  - '-t'
  - 'gcr.io/cbd-test/yo:b'
  - '.'

images:
- 'gcr.io/cbd-test/yo:a'
- 'gcr.io/cbd-test/yo:b'
