steps:
- name: 'gcr.io/cloud-builders/docker'
  id: 'Build'
  args:
  - 'build'
  - '-t'
  - '$_IMAGE_NAME:$SHORT_SHA'
  - '.'
  - '-f'
  - '$_DOCKERFILE_PATH'

- name: 'gcr.io/cloud-builders/docker'
  id: 'Push'
  args:
  - 'push'
  - '$_IMAGE_NAME:$SHORT_SHA'

- name: 'gcr.io/cbd-test/gke-deploy'
  id: 'Deploy'
  args:
  - 'run'
  - '--filename=$_K8S_YAML_PATH'
  - '--image=$_IMAGE_NAME:$SHORT_SHA'
  - '--app=$_K8S_APP_NAME'
  - '--version=$SHORT_SHA'
  - '--output=output'
  - '--namespace=$_K8S_NAMESPACE'
  - '--label=$_K8S_LABELS,gcb-build-id=$BUILD_ID'
  - '--cluster=$_GKE_CLUSTER'
  - '--location=$_GKE_LOCATION'

images:
- '$_IMAGE_NAME:$SHORT_SHA'

artifacts:
  objects:
    location: 'gs://$_OUTPUT_BUCKET/$BUILD_ID'
    paths: ['output/*']

substitutions:
  _DOCKERFILE_PATH: Dockerfile
  _IMAGE_NAME:
  _GKE_CLUSTER:
  _GKE_LOCATION:
  _K8S_YAML_PATH:
  _K8S_APP_NAME:
  _K8S_NAMESPACE:
  _K8S_LABELS:  # Additional labels (key1=val1,key2=val2)
  _OUTPUT_BUCKET:  # Save modified YAMLs for auditing

options:
  substitution_option: 'ALLOW_LOOSE'

tags: ['gcp-cloud-build-deploy', '$_K8S_APP_NAME']
